mysite/blog/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('<int:blog_id>', views.blog_post, name='blog_post'),
    path('blog_list.html/', views.blog_list, name='blog_list'),
    path('archieve_blogs.html/<int:year>/<int:month>', views.archieve_blogs, name='archieve_blogs'),
    # 大类分类显示小类
    path('base_categorys.html/<int:pk>', views.base_categorys, name='base_categorys'),
    # 具体分类下的文章
    path('category.html/<int:id>', views.category_blogs, name='category_blogs'),

    path('all_categorys.html/', views.all_categorys, name='all_categorys'),
    
    path('waiting2.html/', views.waiting2, name='waiting2'),
    path('waiting3.html/', views.waiting3, name='waiting3'),
    path('waiting4.html/', views.waiting4, name='waiting4'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index.html/',views.home,name='home'),
    path('',views.home,name='home'),
    path('blog/', include('blog.urls')),
    path('ckeditor/', include("ckeditor_uploader.urls")),
    # 大类链接
    # path('basetype/', )),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mysite/blog/models.py
from django.db import models
# 导入User
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.
# 富文本编辑引入包
from ckeditor_uploader.fields import RichTextUploadingField
# 类型表，因为外键的关系，类型表要在博客表之前创建
class BaseType(models.Model):
    type_name = models.CharField(max_length=50,verbose_name='类型名称')

    class Meta:
        verbose_name = "博客大类型"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.type_name
class BlogType(models.Model):
    type_name = models.CharField(max_length=50,verbose_name='类型名称')
    base_type = models.ForeignKey(BaseType,null=True,on_delete = models.DO_NOTHING)

    class Meta:
        verbose_name = "博客细类型"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.type_name




# 博客表
class Blog(models.Model):
    title = models.CharField(max_length=30,verbose_name='标题')
    blog_type = models.ForeignKey(BlogType,on_delete = models.DO_NOTHING)
    # content = models.CharField() CharField必须定义max_length
    content = RichTextUploadingField() #正文不限制字数
    author = models.ForeignKey(User,on_delete = models.DO_NOTHING)
    # created_time = models.DateTimeField(auto_now_add = True)
    # last_updated_time = models.DateTimeField(auto_now = True)
    created_time = models.DateTimeField(default = timezone.now,verbose_name='创建日期')
    last_updated_time = models.DateTimeField(default = timezone.now)
    # 是否显示
    # isShow = models.BooleanField(default=True,verbose_name="是否显示")
    class Meta:
        verbose_name="博客表"
        verbose_name_plural=verbose_name

mysite/blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Blog,BlogType,BaseType
from django.core.paginator import Paginator,PageNotAnInteger,InvalidPage,EmptyPage
# Create your views here.
'''设置get方法'''


def gobal(request):
    ''' 获取所有的大分类'''
    base_types = BaseType.objects.all()

    # print(base_categorys)
    
    ''' 获取所有的细分类'''
    all_categorys = BlogType.objects.all()
    # print(all_categorys)
   
    ''
    ''' 获取大分类下的细分类'''
     
    ''' 获取所有的日期'''
    all_dates = Blog.objects.dates("created_time", 'month', order='DESC')
    ''' 获取所有的文章'''
    all_blogs = Blog.objects.all().order_by('-created_time')
    ''' 获取最近五篇文章'''
    recent_blogs = all_blogs[:5]
    '''dates(field, kind, order='ASC')三个参数为：字段，类型，和排序方法，ASC（正序）和DESC（倒序）'''
    all_dates = Blog.objects.dates("created_time", 'month', order='DESC')
    return locals()
'''分页封装方法'''
def pag(request1, objForPag, num):
    '''返回了两个值，有三个参数，调用传入三个参数，并自定义两个两个而接受返回值'''
    '''参数1、网页获取对象，2、需要分页（all_list）的对象，3、分页每页的数据'''
    '''返回值1、获取当页对象，2、循环的页数'''
    '''分页'''
    # 1、实例化分页器 第一个参数是要分页的对象，第二个参数每页的博客对象数量
    paginator = Paginator(objForPag, num)
    # 2、获取当前页码
    try:
        page_num = request1.GET.get("page", 1)
        # 3、通过当前页码获取当页的对象（不是具体数据，所以不能直接得出数量等）
        pageObj = paginator.page(page_num)
        '''实现页码不全部显示，只显示前后两页.默认是全部显示blog_list.paginator.page_range方法全部获得'''
        currentPage = pageObj.number  # 获取当前页码
        # page_range = [max(currentPage-2,1),currentPage-1,currentPage,currentPage+1,currentPage+2]#循环遍历的部分
        page_range = list(range(max(currentPage - 2, 1), currentPage)) + list(
            range(currentPage, min(currentPage + 2, paginator.num_pages) + 1))

        # 加上省略号
        if page_range[0] - 1 >= 2:
            page_range.insert(0, '...')
        if paginator.num_pages - page_range[-1] >= 2:
            page_range.append('...')

        # 加上首尾页码
        if page_range[0] != 1:
            page_range.insert(0, 1)  # 0位置，插入1数字
        if page_range[-1] != paginator.num_pages:
            page_range.append(paginator.num_pages)
    except(PageNotAnInteger, EmptyPage, InvalidPage):
        pageObj = paginator.page(1)
    return (pageObj, page_range)

'''分页结束'''


'''所有分类'''
def all_categorys(request):
    return render(request,'all_categorys.html',locals())
'''文章详情页面'''
def blog_post(request,blog_id):
    # obj = Blog.objects.get(pk = blog_id)
    obj = get_object_or_404(Blog,id = blog_id)
    '''获取上一篇下一篇'''
    blog_prev = Blog.objects.filter(created_time__gt=obj.created_time).first()
    blog_next = Blog.objects.filter(created_time__lt=obj.created_time).last()
    '''显示归档'''
    
    '''显示所属分类'''


    return render(request,'blog_post.html',locals())

'''所有博客列表'''
def blog_list(request):
    # all_categorys = get_all_categorys()
    all_blogs = Blog.objects.all().order_by("-created_time")
    '''分页显示'''
    pageObj, page_range = pag(request,all_blogs,10)
    '''显示归档'''
    

    return render(request,'blog_list.html',locals())

'''归档下博客'''
def archieve_blogs(request,year,month):
    '''显示归档'''
    
    date_blogs = Blog.objects.filter(created_time__year=year, created_time__month=month)
    date = "%s年%s月" % (year, month)
    '''分页显示'''
    pageObj, page_range = pag(request, date_blogs, 10)

    return render(request,'archieve_blogs.html',locals())



'''得到大类下小类'''
def base_categorys(request,pk):

    # 根据大类id，得到该大类下的所有小类
    base_type_name = BaseType.objects.get(pk = pk)#大类

    base_categorys = BlogType.objects.filter(base_type = base_type_name)
    # print(base_categorys)

    return render(request,'base_categorys.html',locals())


def category_blogs(request,id):

    # 1.得到类型---filter得到一个列表(不是对象，不能直接点属性),所以就算只有一个值,也要切片取值
    typename = BlogType.objects.filter(pk = id).first()


    # 2.通过外键得到对象博客
    category_blogs = Blog.objects.filter(blog_type = typename)#过滤器

    '''分页'''
    pageObj, page_range = pag(request, category_blogs, 10)

    # 通过子表（小类型）查询父表（大类型),已知下类型的id
    cateObj = BlogType.objects.get(pk=id) # 得到当前小分类的对象
    
    baseObj = BaseType.objects.get(type_name = cateObj.base_type)#获取当前大类对象
  
    base_categorys = baseObj.blogtype_set.all()


    return render(request,'category_blogs.html',locals())



def bootstrap(request):

    
    return render(request,'bootstrap.html',locals())

# def archives(request):
#     '''显示归档'''
#     
#     return render(request,'archives.html',locals())


def waiting2(request):
    
    '''显示归档'''
    
    return render(request,'waiting2.html',locals())

def waiting3(request):
    
    '''显示归档'''
    
    return render(request,'waiting3.html',locals())

def waiting4(request):
    
    '''显示归档'''
    
    return render(request,'waiting4.html',locals())

mysite/mysite/views.py
from django.shortcuts import render
from blog.models import BlogType,Blog,BaseType

def gobal(request):
    ''' 获取所有的大分类'''
    base_types = BaseType.objects.all()
    # print(base_categorys)
    
    ''' 获取所有的细分类'''
    all_categorys = BlogType.objects.all() 
     
    ''' 获取所有的日期'''
    all_dates = Blog.objects.dates("created_time", 'month', order='DESC')
    ''' 获取所有的文章'''
    all_blogs = Blog.objects.all().order_by('-created_time')
    ''' 获取最近五篇文章'''
    recent_blogs = all_blogs[:5]
    '''dates(field, kind, order='ASC')三个参数为：字段，类型，和排序方法，ASC（正序）和DESC（倒序）'''
    all_dates = Blog.objects.dates("created_time", 'month', order='DESC')
    return locals()

def home(request):
    return render(request,'index.html',locals())





mysite/templates/all_categorys.html
{% extends 'index.html' %}
{% load static from staticfiles %}
{% block title %}所有类型{% endblock %}




{% block left %}
    <div class="left" id="content_wrapper">
				<div id="content">
				{% for category in all_categorys %}
                <div>
                    <a href="{% url 'blog:category_blogs' category.pk %}"><span class="blogtitle">{{ category.type_name }}</span></a>&nbsp;({{ category.blog_set.count }})
                    <span class="time"></span>
                    <br>
                </div>
            	{% endfor %}
				</div>
			</div>
{% endblock %}

mysite/templates/archieve_blogs.html
{% extends 'index.html' %}
{% load static from staticfiles %}
{% block title %}{{ date }}{% endblock %}

{% block nav_pageObj %}current_page_item{% endblock %}



{% block sub %}
    <div id="subnav">
        <ul class="tabbed">
            <li class="current_page_item"><a href="#">当前第&nbsp;{{ pageObj.number }}&nbsp;页，共有&nbsp;{{ pageObj.paginator.num_pages }}&nbsp;页，共有&nbsp;{{ pageObj.paginator.count }}&nbsp;篇博客</a></li>
        </ul>
        <div class="clearer">&nbsp;</div>
    </div>
{% endblock %}

{% block left %}
    <div class="left" id="content_wrapper">
        <div id="content">
            {% for blog in pageObj %}
                <div>
                    <a href="{% url 'blog:blog_post' blog.pk %}"><span class="blogtitle">{{ blog.title }}</span></a>
                    <span class="time">{{ blog.created_time|date:"Y-m-d" }}</span>
                    <br>
                </div>
            {% endfor %}
        </div>

        <!--分页开始-->
        {#分页#}
        <div class="paginator">
            <ul class="pagination">
                <!-- 上一页 -->
            <!--pageObj,views里的当页对象-->
                <li>
                    {% if pageObj.has_previous %}
                        <a href="?page={{ pageObj.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    {% else %}
                        <span aria-hidden="true">&laquo;</span>
                    {% endif %}
                </li>
                <!-- 页码遍历和当前页码 1、全部遍历 2、只遍历前后两个 -->
                {#          1、 {% for page_num in pageObj.paginator.page_range %} #}
                <!-- 2、 -->
                {% for page_num in page_range %}
                    <!-- 判断是否当前页面，实现当前页的页码高亮 -->
                    {% if page_num == pageObj.number %}
                        <li class="active"><span>{{ page_num }}</span></li>
                    {% else %}
                        <!-- 判断是否是省略号 -->
                        {% if page_num == '...' %}
                            <li><span>{{ page_num }}</span></li>
                        {% else %}
                            <li><a href="?page={{ page_num }}">{{ page_num }}</a></li>
                        {% endif %}

                    {% endif %}
                {% endfor %}

                <!-- 下一页 -->
                <li>
                    {% if pageObj.has_next %}
                        <a href="?page={{ pageObj.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    {% else %}
                        <span aria-hidden="true">&raquo;</span>
                    {% endif %}
                </li>
            </ul>
            {#  1、num_pages和2、count的用处， 1、单页对象-》分页器-》分的总页数  2、单页对象-》分页器-》被分页的对象的数量（对象数量） #}
{#            <p>#}
{#                当前第&nbsp;{{ pageObj.number }}&nbsp;页，共有&nbsp;{{ pageObj.paginator.num_pages }}&nbsp;页，共有&nbsp;{{ pageObj.paginator.count }}&nbsp;篇博客</p>#}
        </div>
        {#分页结束#}

        <!--分页结束-->
    </div>
{% endblock %}







mysite/templates/archives.html
{% extends 'index.html' %}
{% load static from staticfiles %}
{% block title %}Django{% endblock %}
{% block nav_django %}current_page_item{% endblock %}

{% block sub %}
    <div id="subnav">
        <ul class="tabbed">
            {% for category in all_categorys %}
                <li class="current_page_item"><a
                        href="{% url 'blog:category_blogs' category.pk %}">{{ category.type_name }}</a></li>
            {% endfor %}
        </ul>
        <div class="clearer">&nbsp;</div>
    </div>
{% endblock %}

{% block left %}
    <div class="left" id="content_wrapper">
        <div id="content">

            {% for category in all_categorys %}
                <div>
                    <a href="{% url 'blog:category_blogs' category.pk %}"><span class="blogtitle">{{ category.type_name }}</span></a>&nbsp;({{ category.blog_set.count }})
                    <span class="time"></span>
                    <br>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}





mysite/templates/base_categorys.html
{% extends 'index.html' %}
{% load static from staticfiles %}
{% block title %}{{base_type_name}}内容{% endblock %}
{% block style %}
        <style type="text/css">
            span.blogtitle {
                font-size: 20px;
                #font-family: '宋体'
            }
            p.empty {
                align-content: : center;
            }

        </style>
{% endblock %}

{% block sub %}
    <div id="subnav">
        <ul class="tabbed"> 
            {% for cat in base_categorys %}
            <li class="current_page_item"><a href="{% url 'blog:category_blogs' cat.pk %}">{{cat.type_name}}</a></li>
            {% endfor %}
        </ul>
        <div class="clearer">&nbsp;</div>
    </div>
{% endblock %}


{% block left %}
    <div class="left" id="content_wrapper">
        <div id="content">

            {% for category in base_categorys %}
                <div>
                    <a href="{% url 'blog:category_blogs' category.pk %}"><span class="blogtitle">{{ category.type_name }}</span></a>&nbsp;({{ category.blog_set.count }})
                    <span class="time"></span>
                    <br>
                </div>
{%empty%}
            <h3 style="text-align:center;">---暂无详细内容（子分类）---</h3>
            {% endfor %}
        </div>
    </div>
{% endblock %}

mysite/templates/blog_list.html
{% extends 'index.html' %}
{% load static from staticfiles %}
{% block title %}pageObj{% endblock %}
{% block test %}list{% endblock %}
{% block nav_pageObj %}current_page_item{% endblock %}



{% block sub %}
    <div id="subnav">
        <ul class="tabbed">
            <li class="current_page_item"><a href="#">学习笔记</a></li>
            <li><a href="#">学习资料</a></li>
        </ul>
        <div class="clearer">&nbsp;</div>
    </div>
{% endblock %}

{% block left %}
    <div class="left" id="content_wrapper">
        <div id="content">
            {% for blog in pageObj %}
                <div>
                    <a href="{% url 'blog:blog_post' blog.pk %}"><span class="blogtitle">{{ blog.title }}</span></a>
                    <span class="time">{{ blog.created_time|date:"Y-m-d" }}</span>
                    <br>
                </div>
            {% endfor %}
        </div>

        <!--分页开始-->
        {#分页#}
        <div class="paginator">
            <ul class="pagination">
                <!-- 上一页 -->
                <li>
                    {% if pageObj.has_previous %}
                        <a href="?page={{ pageObj.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    {% else %}
                        <span aria-hidden="true">&laquo;</span>
                    {% endif %}
                </li>
                <!-- 页码遍历和当前页码 1、全部遍历 2、只遍历前后两个 -->
                {#          1、 {% for page_num in pageObj.paginator.page_range %} #}
                <!-- 2、 -->
                {% for page_num in page_range %}
                    <!-- 判断是否当前页面，实现当前页的页码高亮 -->
                    {% if page_num == pageObj.number %}
                        <li class="active"><span>{{ page_num }}</span></li>
                    {% else %}
                        <!-- 判断是否是省略号 -->
                        {% if page_num == '...' %}
                            <li><span>{{ page_num }}</span></li>
                        {% else %}
                            <li><a href="?page={{ page_num }}">{{ page_num }}</a></li>
                        {% endif %}

                    {% endif %}
                {% endfor %}

                <!-- 下一页 -->
                <li>
                    {% if pageObj.has_next %}
                        <a href="?page={{ pageObj.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    {% else %}
                        <span aria-hidden="true">&raquo;</span>
                    {% endif %}
                </li>
            </ul>
            {#  1、num_pages和2、count的用处， 1、单页对象-》分页器-》分的总页数  2、单页对象-》分页器-》被分页的对象的数量（对象数量） #}
            <p>
                当前第&nbsp;{{ pageObj.number }}&nbsp;页，共有&nbsp;{{ pageObj.paginator.num_pages }}&nbsp;页，共有&nbsp;{{ pageObj.paginator.count }}&nbsp;篇博客</p>
        </div>
        {#分页结束#}

        <!--分页结束-->
    </div>
{% endblock %}







mysite/templates/bootstrap.html
{% extends 'index.html' %}
{% load static from staticfiles %}
{% block title %}Django{% endblock %}
<!-- {% block nav %}current_page_item{% endblock %} -->

{% block sub %}
    <div id="subnav">
        <ul class="tabbed">
            {% for category in bootstrap_categorys %}
                <li class="{% block django %}{% endblock%}"><a
                        href="{% url 'blog:category_blogs' category.pk %}">{{ category.type_name }}</a></li>
            {% endfor %}
        </ul>
        <div class="clearer">&nbsp;</div>
    </div>
{% endblock %}

{% block left %}
    <div class="left" id="content_wrapper">
        <div id="content">

            {% for category in bootstrap_categorys %}
                <div>
                    <a href="{% url 'blog:category_blogs' category.pk %}"><span class="blogtitle">{{ category.type_name }}</span></a>&nbsp;({{ category.blog_set.count }})
                    <span class="time"></span>
                    <br>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}





mysite/templates/category_detail.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
category_detail
</body>
</html>

mysite/templates/index.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
    <meta name="description" content=""/>
    <meta name="keywords" content=""/>
    <meta name="author" content=""/>
    <link rel="icon" type="image/x-icon" href="{% static 'img/ico.ico' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" media="screen"/>
    <script type="text/javascript" src="{% static 'jquery-1.12.4.min.js' %}"></script>


    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <style type="text/css">
                    li{
                list-style: none;
            }
    </style>
    {% block style %}
        <style type="text/css">
            span.blogtitle {
                font-size: 20px;
                #font-family: '宋体'
            }
            span.time {
                /*
            {#span 和label类似是文字标签不是浮层，默认宽度就文字那么宽所以你设置文字居右没有效果，让span漂浮可以达到你的效果吧，float:right#}        */
                float: right;
            }

        </style>
    {% endblock %}

    <title>{% block title %}个人博客{% endblock %}</title>
</head>

<body id="top">
<div id="layout_wrapper">
    <div id="layout_wrapper2">
        <div id="layout_wrapper3">
            <div id="layout_wrapper4">
                <div id="navigation">
                    <div id="nav">
                        <ul class="tabbed">
                            <li><a href="{% url 'home' %}">首页</a></li>
                            <li> <a href="{% url 'blog:blog_list' %}">所有博客</a>
                            </li>
                            {% for base in base_types %}

                            <li><a href="{% url 'blog:base_categorys' base.pk %}">{{base.type_name}}</a></li>
                            {% endfor %}
                            <li><a href="{% url 'blog:all_categorys' %}">所有分类</a></li>
                        </ul>
                        <div class="clearer">&nbsp;</div>
                    </div>
                    <!-- 子页面 -->
                    {% block sub %}
                        <div id="subnav">
                            <ul class="tabbed">
                                <li class="current_page_item"><a href="#">首页子页面</a></li>
                                <li><a href="#">首页子页面</a></li>
                                <li><a href="#">首页子页面</a></li>
                                <li><a href="#">首页子页面</a></li>
                            </ul>
                            <div class="clearer">&nbsp;</div>
                        </div>
                    {% endblock %}
                    <!-- 子页面 -->
                </div>
                <div id="main_wrapper">
                    <div id="main">
                        <!--正文-->
                        {% block left %}
                            <div class="left" id="content_wrapper">
                                <div id="content">
                                    <div class="post">
                                        <div class="post_title"><h3>最新文章</h3></div>

                                        {% for blog in recent_blogs %}
                                            <div>
                                                <a href="{% url 'blog:blog_post' blog.pk %}"><span
                                                        class="blogtitle">{{ blog.title }}</span></a>
                                                <span class="time">{{ blog.created_time|date:"Y-m-d" }}</span>
                                                <br>
                                            </div>
                                        {% endfor %}
                                        <div class="post_body">
                                        </div>
                                        <div class="post_meta">
                                            <a href="#">占位</a> | Tagged: <a href="#">Sapien</a>, <a href="#">Sollicitudin</a>
                                            <a href="#">占位</a>
                                        </div>

                                    </div>

                                    <div class="post">
                                        <div class="post_title"><h3><a href="#">最热文章</a></h3></div>
                                        <div class="post_date">Posted on Dec 11th at 16:12 from <a href="#">Aliquet
                                            Quis</a>
                                        </div>
                                        <div class="post_body">
                                        </div>
                                        <div class="post_meta">
                                            <a href="#">11 comments</a> | Tagged: <a href="#">Purus</a>, <a
                                                href="#">Semper</a>, <a href="#">Vestibulum</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endblock %}
                        <!--正文-->
                        <!--右边栏-->

                        <div class="right" id="sidebar_wrapper">
                            <div id="sidebar">

                                <div class="box">
                                    <div class="box_title">个人博客</div>
                                    <div class="box_content">
                                        <p>微信:AutccnNight</p>
                                        <p>邮箱:838626049@qq.com</p>
                                        <p>邮箱:lsy1210@aliyun.com</p>
                                    </div>
                                </div>
                                <div class="box">
                                    <div class="box_title">学习内容</div>
                                    <div class="box_content">
                                        {% for base in base_types%}         
                                        <ul>
                                            <li><a href="{% url 'blog:base_categorys' base.pk %}">{{ base.type_name}}</a></li>                          
                                        </ul>
                                         {% endfor %}
                                    </div>
                                </div>
                                <div class="box">
                                    <div class="box_title">归档</div>
                                    <div class="box_content">
                                        <ul>
                                            {% for date in all_dates %}
                                                <li>
                                                    <a href="{% url 'blog:archieve_blogs' date.year date.month %}">
                                                        {{ date|date:"Y年m月" }}</a>&nbsp;&nbsp;
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </div>

                                </div>

                            </div>
                        </div>
                        <!--右边栏-->

                        <div class="clearer">&nbsp;</div>
                    </div>
                </div>


                <div id="footer">
                    <div class="left">
                        &copy; #
                    </div>
                    <div class="right">
                        <a href="#">#</a> # <a href="#">#</a>
                    </div>
                    <div class="clearer">&nbsp;</div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

mysite/templates/waiting3.html
{% extends 'index.html' %}
{% load static from staticfiles %}

{% block nav_waiting3 %}current_page_item{% endblock %}

{% block left %}
    <div class="left" id="content_wrapper">
				<div id="content">

					<h1>Empty Page</h1>

					<p>Nothing to be found here..</p>

				</div>
			</div>
{% endblock %}



mysite/templates/waiting4.html
{% extends 'index.html' %}
{% load static from staticfiles %}

{% block nav_waiting4 %}current_page_item{% endblock %}

{% block left %}
    <div class="left" id="content_wrapper">
				<div id="content">

					<h1>Empty Page</h1>

					<p>Nothing to be found here..</p>

				</div>
			</div>
{% endblock %}

